[package]
name = "near-lottery"
version = "0.1.0"
authors = ["NEAR Lottery"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.0.0"
near-contract-standards = "5.0.0"
borsh = "1.5.0" 